services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: flashcard_db
        ports:
            - 27017:27017
        volumes:
            - ./mongodata:/data/db
            - ./001_initial.js:/docker-entrypoint-initdb.d/001_initial.js
        command: [--auth]
